//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BantamRouter.NavWSsEmployee {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Employees_Binding", Namespace="urn:microsoft-dynamics-schemas/page/employees")]
    public partial class Employees_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Employees_Service() {
            this.Url = global::BantamRouter.Properties.Settings.Default.BantamRouter_NavWSsEmployee_Employees_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/employees:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/employees", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/employees", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Employees")]
        public Employees Read(string No) {
            object[] results = this.Invoke("Read", new object[] {
                        No});
            return ((Employees)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string No) {
            this.ReadAsync(No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/employees:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/employees", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/employees", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Employees")]
        public Employees ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((Employees)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/employees:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/employees", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/employees", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Employees[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] Employees_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((Employees[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(Employees_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(Employees_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/employees:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/employees", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/employees", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/employees:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/employees", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/employees", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/employees")]
    public partial class Employees {
        
        private string keyField;
        
        private string noField;
        
        private string fullNameField;
        
        private string first_NameField;
        
        private string middle_NameField;
        
        private string last_NameField;
        
        private string initialsField;
        
        private string job_TitleField;
        
        private string post_CodeField;
        
        private string country_Region_CodeField;
        
        private string extensionField;
        
        private string phone_NoField;
        
        private string mobile_Phone_NoField;
        
        private string e_MailField;
        
        private string statistics_Group_CodeField;
        
        private string resource_NoField;
        
        private string search_NameField;
        
        private bool commentField;
        
        private bool commentFieldSpecified;
        
        private string addressField;
        
        private string cityField;
        
        private string countyField;
        
        private System.DateTime birth_DateField;
        
        private bool birth_DateFieldSpecified;
        
        private string social_Security_NoField;
        
        private Gender genderField;
        
        private bool genderFieldSpecified;
        
        private string emplymt_Contract_CodeField;
        
        private System.DateTime employment_DateField;
        
        private bool employment_DateFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private System.DateTime inactive_DateField;
        
        private bool inactive_DateFieldSpecified;
        
        private System.DateTime termination_DateField;
        
        private bool termination_DateFieldSpecified;
        
        private string global_Dimension_1_CodeField;
        
        private string global_Dimension_2_CodeField;
        
        private string fax_NoField;
        
        private string company_E_MailField;
        
        private string titleField;
        
        private string salespers_Purch_CodeField;
        
        private string nSSF_NoField;
        
        private string nHIF_NoField;
        
        private string pIN_NoField;
        
        private string national_IDField;
        
        private string hELB_NoField;
        
        private string sacco_Co_op_NoField;
        
        private string hR_Posting_GroupField;
        
        private string payroll_Posting_GroupField;
        
        private string designationField;
        
        private string passport_NoField;
        
        private string gradeField;
        
        private string imprest_UserIDField;
        
        private string job_IDField;
        
        private System.DateTime contract_Start_DateField;
        
        private bool contract_Start_DateFieldSpecified;
        
        private System.DateTime contract_End_DateField;
        
        private bool contract_End_DateFieldSpecified;
        
        private string notice_PeriodField;
        
        private System.DateTime exit_Interview_DateField;
        
        private bool exit_Interview_DateFieldSpecified;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private string webUserIDField;
        
        private string base_CalendarField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string First_Name {
            get {
                return this.first_NameField;
            }
            set {
                this.first_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Middle_Name {
            get {
                return this.middle_NameField;
            }
            set {
                this.middle_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Last_Name {
            get {
                return this.last_NameField;
            }
            set {
                this.last_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        public string Job_Title {
            get {
                return this.job_TitleField;
            }
            set {
                this.job_TitleField = value;
            }
        }
        
        /// <remarks/>
        public string Post_Code {
            get {
                return this.post_CodeField;
            }
            set {
                this.post_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country_Region_Code {
            get {
                return this.country_Region_CodeField;
            }
            set {
                this.country_Region_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        public string Phone_No {
            get {
                return this.phone_NoField;
            }
            set {
                this.phone_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile_Phone_No {
            get {
                return this.mobile_Phone_NoField;
            }
            set {
                this.mobile_Phone_NoField = value;
            }
        }
        
        /// <remarks/>
        public string E_Mail {
            get {
                return this.e_MailField;
            }
            set {
                this.e_MailField = value;
            }
        }
        
        /// <remarks/>
        public string Statistics_Group_Code {
            get {
                return this.statistics_Group_CodeField;
            }
            set {
                this.statistics_Group_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Resource_No {
            get {
                return this.resource_NoField;
            }
            set {
                this.resource_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Search_Name {
            get {
                return this.search_NameField;
            }
            set {
                this.search_NameField = value;
            }
        }
        
        /// <remarks/>
        public bool Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommentSpecified {
            get {
                return this.commentFieldSpecified;
            }
            set {
                this.commentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Birth_Date {
            get {
                return this.birth_DateField;
            }
            set {
                this.birth_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Birth_DateSpecified {
            get {
                return this.birth_DateFieldSpecified;
            }
            set {
                this.birth_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Social_Security_No {
            get {
                return this.social_Security_NoField;
            }
            set {
                this.social_Security_NoField = value;
            }
        }
        
        /// <remarks/>
        public Gender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Emplymt_Contract_Code {
            get {
                return this.emplymt_Contract_CodeField;
            }
            set {
                this.emplymt_Contract_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Employment_Date {
            get {
                return this.employment_DateField;
            }
            set {
                this.employment_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Employment_DateSpecified {
            get {
                return this.employment_DateFieldSpecified;
            }
            set {
                this.employment_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Inactive_Date {
            get {
                return this.inactive_DateField;
            }
            set {
                this.inactive_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Inactive_DateSpecified {
            get {
                return this.inactive_DateFieldSpecified;
            }
            set {
                this.inactive_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Termination_Date {
            get {
                return this.termination_DateField;
            }
            set {
                this.termination_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Termination_DateSpecified {
            get {
                return this.termination_DateFieldSpecified;
            }
            set {
                this.termination_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Global_Dimension_1_Code {
            get {
                return this.global_Dimension_1_CodeField;
            }
            set {
                this.global_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Global_Dimension_2_Code {
            get {
                return this.global_Dimension_2_CodeField;
            }
            set {
                this.global_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Fax_No {
            get {
                return this.fax_NoField;
            }
            set {
                this.fax_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Company_E_Mail {
            get {
                return this.company_E_MailField;
            }
            set {
                this.company_E_MailField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Salespers_Purch_Code {
            get {
                return this.salespers_Purch_CodeField;
            }
            set {
                this.salespers_Purch_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string NSSF_No {
            get {
                return this.nSSF_NoField;
            }
            set {
                this.nSSF_NoField = value;
            }
        }
        
        /// <remarks/>
        public string NHIF_No {
            get {
                return this.nHIF_NoField;
            }
            set {
                this.nHIF_NoField = value;
            }
        }
        
        /// <remarks/>
        public string PIN_No {
            get {
                return this.pIN_NoField;
            }
            set {
                this.pIN_NoField = value;
            }
        }
        
        /// <remarks/>
        public string National_ID {
            get {
                return this.national_IDField;
            }
            set {
                this.national_IDField = value;
            }
        }
        
        /// <remarks/>
        public string HELB_No {
            get {
                return this.hELB_NoField;
            }
            set {
                this.hELB_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Sacco_Co_op_No {
            get {
                return this.sacco_Co_op_NoField;
            }
            set {
                this.sacco_Co_op_NoField = value;
            }
        }
        
        /// <remarks/>
        public string HR_Posting_Group {
            get {
                return this.hR_Posting_GroupField;
            }
            set {
                this.hR_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Payroll_Posting_Group {
            get {
                return this.payroll_Posting_GroupField;
            }
            set {
                this.payroll_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
            }
        }
        
        /// <remarks/>
        public string Passport_No {
            get {
                return this.passport_NoField;
            }
            set {
                this.passport_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        public string Imprest_UserID {
            get {
                return this.imprest_UserIDField;
            }
            set {
                this.imprest_UserIDField = value;
            }
        }
        
        /// <remarks/>
        public string Job_ID {
            get {
                return this.job_IDField;
            }
            set {
                this.job_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Contract_Start_Date {
            get {
                return this.contract_Start_DateField;
            }
            set {
                this.contract_Start_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Contract_Start_DateSpecified {
            get {
                return this.contract_Start_DateFieldSpecified;
            }
            set {
                this.contract_Start_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Contract_End_Date {
            get {
                return this.contract_End_DateField;
            }
            set {
                this.contract_End_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Contract_End_DateSpecified {
            get {
                return this.contract_End_DateFieldSpecified;
            }
            set {
                this.contract_End_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Notice_Period {
            get {
                return this.notice_PeriodField;
            }
            set {
                this.notice_PeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Exit_Interview_Date {
            get {
                return this.exit_Interview_DateField;
            }
            set {
                this.exit_Interview_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Exit_Interview_DateSpecified {
            get {
                return this.exit_Interview_DateFieldSpecified;
            }
            set {
                this.exit_Interview_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Last_Date_Modified {
            get {
                return this.last_Date_ModifiedField;
            }
            set {
                this.last_Date_ModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified {
            get {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_ModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string WebUserID {
            get {
                return this.webUserIDField;
            }
            set {
                this.webUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string Base_Calendar {
            get {
                return this.base_CalendarField;
            }
            set {
                this.base_CalendarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/employees")]
    public enum Gender {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Female,
        
        /// <remarks/>
        Male,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/employees")]
    public enum Status {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Inactive,
        
        /// <remarks/>
        Terminated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/employees")]
    public partial class Employees_Filter {
        
        private Employees_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public Employees_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/employees")]
    public enum Employees_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        FullName,
        
        /// <remarks/>
        First_Name,
        
        /// <remarks/>
        Middle_Name,
        
        /// <remarks/>
        Last_Name,
        
        /// <remarks/>
        Initials,
        
        /// <remarks/>
        Job_Title,
        
        /// <remarks/>
        Post_Code,
        
        /// <remarks/>
        Country_Region_Code,
        
        /// <remarks/>
        Extension,
        
        /// <remarks/>
        Phone_No,
        
        /// <remarks/>
        Mobile_Phone_No,
        
        /// <remarks/>
        E_Mail,
        
        /// <remarks/>
        Statistics_Group_Code,
        
        /// <remarks/>
        Resource_No,
        
        /// <remarks/>
        Search_Name,
        
        /// <remarks/>
        Comment,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        County,
        
        /// <remarks/>
        Birth_Date,
        
        /// <remarks/>
        Social_Security_No,
        
        /// <remarks/>
        Gender,
        
        /// <remarks/>
        Emplymt_Contract_Code,
        
        /// <remarks/>
        Employment_Date,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Inactive_Date,
        
        /// <remarks/>
        Termination_Date,
        
        /// <remarks/>
        Global_Dimension_1_Code,
        
        /// <remarks/>
        Global_Dimension_2_Code,
        
        /// <remarks/>
        Fax_No,
        
        /// <remarks/>
        Company_E_Mail,
        
        /// <remarks/>
        Title,
        
        /// <remarks/>
        Salespers_Purch_Code,
        
        /// <remarks/>
        NSSF_No,
        
        /// <remarks/>
        NHIF_No,
        
        /// <remarks/>
        PIN_No,
        
        /// <remarks/>
        National_ID,
        
        /// <remarks/>
        HELB_No,
        
        /// <remarks/>
        Sacco_Co_op_No,
        
        /// <remarks/>
        HR_Posting_Group,
        
        /// <remarks/>
        Payroll_Posting_Group,
        
        /// <remarks/>
        Designation,
        
        /// <remarks/>
        Passport_No,
        
        /// <remarks/>
        Grade,
        
        /// <remarks/>
        Imprest_UserID,
        
        /// <remarks/>
        Job_ID,
        
        /// <remarks/>
        Contract_Start_Date,
        
        /// <remarks/>
        Contract_End_Date,
        
        /// <remarks/>
        Notice_Period,
        
        /// <remarks/>
        Exit_Interview_Date,
        
        /// <remarks/>
        Last_Date_Modified,
        
        /// <remarks/>
        WebUserID,
        
        /// <remarks/>
        Base_Calendar,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employees Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employees)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employees Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employees)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employees[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employees[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591